### ISSUE TITLE
Mac 系统下不好用啊

### ISSUE THREAD

**Issue by caoyifeng007** [SweetInk/lagou-course-downloader#17]

**Comment by SweetInk** [comment]
有啥问题吗，请描述出来

**Comment by sunHappy** [comment]
MAC系统提示错误
Exception in thread "main" java.lang.NullPointerException
	at online.githuboy.lagou.course.support.Course.getAllCoursePurchasedRecordForPC(Course.java:50)
	at online.githuboy.lagou.course.App.main(App.java:38)

**Comment by SweetInk** [comment]
@sunHappy 拉下最新代码试试

**Comment by sunHappy** [comment]
就是刚下载的新代码  不会是刚刚你更新了吧 @SweetInk

**Comment by SweetInk** [comment]
@sunHappy 已经定位到问题了，你在config.properties文件中把`courseIds`的值给加上试试（你要下载的课程id）

**Comment by sunHappy** [comment]
![截屏2021-06-30 下午4 44 08](https://user-images.githubusercontent.com/12652923/123930537-71bc9800-d9c2-11eb-910c-64fc2551a76c.png)
@SweetInk  运行起来了 不过没有下载到视频文件 是因为什么

**Comment by SweetInk** [comment]
@sunHappy 控制台有错误信息输出吗？

**Comment by sunHappy** [comment]
![截屏2021-06-30 下午4 54 26](https://user-images.githubusercontent.com/12652923/123932404-007de480-d9c4-11eb-9fcd-d812ec56696d.png)
有一些类似的error提示 java我还没有学过 不太懂 麻烦大佬的解答了

**Comment by SweetInk** [comment]
看下控制台类似这样的关键字信息:`获取视频:【xxx】信息失败`

**Comment by sunHappy** [comment]
![截屏2021-06-30 下午5 01 20](https://user-images.githubusercontent.com/12652923/123933333-dda00000-d9c4-11eb-8c7c-ea1555e0e6b9.png)
@SweetInk 有这样的信息

**Comment by SweetInk** [comment]
@sunHappy 你加我qq（2910226337）沟通吧，这个上面沟通效率有点低
