### ISSUE TITLE
这个怎么解决？复制错误 Cookies？

### ISSUE THREAD

**Issue by AndersonHJB** [SweetInk/lagou-course-downloader#41]
"state": 1111,
  "message": "上次登录IP：183.251.31.224"
}
Exception in thread "main" java.lang.RuntimeException: 获取已购课程失败:上次登录IP：183.251.31.224
	at online.githuboy.lagou.course.request.HttpAPI.getPurchasedCourseRecord(HttpAPI.java:180)
	at online.githuboy.lagou.course.support.Course.getAllCoursePurchasedRecordForPC(Course.java:23)
	at online.githuboy.lagou.course.App.main(App.java:37)

**Comment by SweetInk** [comment]
这个不知道是不是ip被ban了。。

**Comment by SweetInk** [comment]
我可以正常下载

**Comment by AndersonHJB** [comment]
不会呀，我第一次使用你这个脚本，你的 cookie 是在哪个文件 copy 的？

**Comment by SweetInk** [comment]
你登陆拉钩后需要把cookie复制到`config.properties`中的`cookie`属性里

**Comment by AndersonHJB** [comment]
拉钩的哪个文件里面？
![image](https://user-images.githubusercontent.com/48122016/133873400-eec5a362-42d6-40c2-adbc-04b5c8807384.png)

**Comment by AndersonHJB** [comment]
就是 拉勾的哪个文件里面复制出 cookies，我不知道是不是我复制错了

**Comment by SweetInk** [comment]
登录成功到你的课程列表有个`getAllCoursePurchasedRecordForPC`这个接口。

**Comment by AndersonHJB** [comment]
嗯嗯，果然 需要抓包才有这个文件
