### ISSUE TITLE
Java高薪训练营下载出错了

### ISSUE THREAD

**Issue by UIT2016wanghui** [SweetInk/lagou-course-downloader#53]
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/26360478/168240749-a8ae6798-6a1f-4e7c-acd0-68b3de4143a8.png">

16:12:14.585 default [main] DEBUG at cn.hutool.setting.SettingLoader.load (SettingLoader.java:80) - Load setting file [file:/Users/wolffy/code/IdeaProjects/lagoudownload-test/lagoudownload/target/classes/config/config.properties]
Exception in thread "main" java.lang.NullPointerException
	at online.githuboy.lagou.course.support.BigCourseDownloader.parseBigCourseLessonInfo(BigCourseDownloader.java:210)
	at online.githuboy.lagou.course.support.BigCourseDownloader.start(BigCourseDownloader.java:93)
	at online.githuboy.lagou.course.App_XunLianYing.main(App_XunLianYing.java:40)

**Comment by robertdeng1212** [comment]
空指针异常，在 BigCourseDownloader.java 211 加个容错处理 if (lessonInfoVoList != null && !lessonInfoVoList.isEmpty()) {

![image](https://user-images.githubusercontent.com/31593084/185350715-331ec68b-2bc1-41c3-b45f-18e84d41e8f4.png)

**Comment by Jc826** [comment]
下载高薪训练营的同学 有没有遇到过
`10:29:47.391 default [pool-1-thread-10] INFO  at online.githuboy.lagou.course.task.BigCourseVideoInfoLoader.run (BigCourseVideoInfoLoader.java:136) -  video:【47_48766_自定义RPC框架-需求分析与基础环境介绍】最大重试结束:3
10:29:47.391 default [pool-1-thread-10] INFO  at online.githuboy.lagou.course.task.BigCourseVideoInfoLoader.run (BigCourseVideoInfoLoader.java:78) - 获取视频信息URL:【562】url：https://gate.lagou.com/v1/neirong/edu/bigcourse/getPlayRecord?courseId=4&weekId=34&dayId=491&lessonId=562&bigCourseMediaUseType=LUBO
10:29:47.402 default [pool-1-thread-13] ERROR at online.githuboy.lagou.course.task.BigCourseVideoInfoLoader.run (BigCourseVideoInfoLoader.java:125) - 获取视频:【51_48770_自定义RPC框架-客户端业务处理类实现】信息失败:
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>GatW</center>
</body>
</html>







	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1510)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
	at com.alibaba.fastjson.JSON.parse(JSON.java:181)
	at com.alibaba.fastjson.JSON.parse(JSON.java:191)
	at com.alibaba.fastjson.JSON.parse(JSON.java:147)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)`
